title: 石榴骑士的个人博客
subtitle: 面向工资编程
description: >- # this means to ignore newlines until "baseurl:"
  
author: 石榴骑士
email: liyuqihxc@gmail.com
avatar: assets/images/avatar.jpg

lang: zh-Hans
repository: liyuqihxc/liyuqihxc.github.io
timezone: Asia/Shanghai
encoding: "utf-8"
baseurl: ""
blogbaseurl: "/blog"
url: "http://liyuqihxc.github.io"
exclude: ['Gemfile','Gemfile.lock']
permalink: /:year/:month/:day/:title/
defaults:
  -
    scope:
      path: "blog/categories" # an empty string means all files in the project
    values:
      hide: true
      layout: "blog"
  -
    scope:
      path: "blog/_posts"
    values:
      hide: true
      layout: post
      permalink: /blog/:year/:month/:day/:title/

# Social settings
facebook_url:
github_url: http://github.com/liyuqihxc
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Google Analytics Tracking ID goes here:
google_analytics: UA-114908873-1

plugins:
#  - jekyll-redirect-from

markdown: kramdown
kramdown:
  input: GFM 
  syntax_highlighter: rouge
highlighter: rouge
excerpt_separator: "<!--excerpt-->"

collections: [sections]
