# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
blogbaseurl: "/blog"
careerurl: "/career"
images: "/blog/img"
skill_images: "/img/skills"
frontage_images: "/img"
url: "http://liyuqihxc.github.io" # the base hostname & protocol for your site
encoding: utf-8
repository: liyuqihxc/liyuqihxc.github.io
timezone: Asia/Shanghai
lang: zh-CN
exclude: ['Gemfile','Gemfile.lock']

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      enable_comments: false

# metatheme-SPECIFIC CONFIGURATION
metatheme:
  # Meta
  title: 石榴骑士的小站
  subtitle: 面向工资编程
  author: 石榴骑士
  avatar: avatar.jpg
  gravatar: # Email MD5 hash
  description: "" # used by search engines

  # Header and footer text
  footer_text: Powered by <a href="http://jekyllrb.com">Jekyll</a>

  # Icons
  rss: false
  email_address: liyuqihxc@gmail.com
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "liyuqihxc"
  google_plus:
  instagram:
  linkedin:
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  twitter: 
  wordpress:
  youtube:

  # Scripts
  google_analytics: UA-114908873-1
  mathjax: true # Enable if using math markup

  # Localization strings
  str_follow_on: "关注"
  str_rss_follow: "订阅 RSS"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Previous"
  str_continue_reading: "Read More"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"

# PAGINATION
permalink: /blog/:categories/:year/:month/:day/:title.html
paginate: 10
paginate_path: "blog/:num"
paginate_category: "blog"
plugins: 
  - jekyll-paginate

# BUILD SETTINGS
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
excerpt_separator: <!--excerpt-->
